Add DL features to documents
UtrechtUniversity/animal-sounds pull request #49
Opened 2024-06-26 14:25 UTC by parisa-zahedi

2024-06-27 06:56 UTC, jelletreep requested changes
Hi Parisa,
Looks good! I added some suggestions for the README, if you agree you can click commit suggestion

2024-06-27 06:56 UTC, jelletreep commented on bioacoustics/feature_extraction/README.md
> +To extract audio features for CNN classifier, .wav files are converted to Log-mel Spectrograms using [librosa](https://zenodo.org/badge/latestdoi/6309729) library.
```suggestion
To extract audio features for CNN classifier, .wav files are converted to Log-mel Spectrograms using [librosa](https://zenodo.org/badge/latestdoi/6309729). 
```

2024-06-27 06:56 UTC, jelletreep commented on bioacoustics/feature_extraction/README.md
> +Log- Melspectrograms had the best results in [[1]](#ref). As a future work we can try others such as Log-Spectrograms, and Gammatone-Spectrogram.
```suggestion
Log-Melspectrograms had the best results in [[1]](#ref). As a future work we can try others such as Log-Spectrograms, and Gammatone-Spectrograms.
```

2024-06-27 06:56 UTC, jelletreep commented on bioacoustics/feature_extraction/README.md
> +In this process, first we apply butter_bandpass filter to select frequencies among 100, 2000 hz. Then the short time Fourier transform (STFT) is applied on time-domain waveforms to calculate spectrog
```suggestion
In this study, first we apply a [Butterworth (bandpass) filter](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.butter.html) to filter frequencies between 100 and 2000 hz for further processing. Then the short time Fourier transform (STFT) is applied to create spectrograms. 
```

2024-06-27 06:56 UTC, jelletreep commented on bioacoustics/feature_extraction/README.md
> +Then mel filter banks are applied on the spectrograms followed by a logarithmic operation to extract log mel spectrograms.
```suggestion
Then we convert the spectrograms to MFCC (Mel-Frequency Cepstral coefficient) representation, which is often done for speech processing (Find more info [here](https://speechprocessingbook.aalto.fi/Representations/Melcepstrum.html)).
```

2024-06-28 08:33 UTC, parisa-zahedi commented
thanks Jelle, for the comments! I committed all!

2024-07-01 07:07 UTC, jelletreep approved these changes

2024-07-01 07:08 UTC, merged